name: Nightly Release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * *' # Runs at 1:00 PM UTC every day

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: package.json

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin, x86_64-apple-darwin

      - name: Rust Cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: src-tauri

      - name: Install Dependencies
        run: bun install

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Build and Release
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: nightly-v${{ steps.date.outputs.date }}
          releaseName: 'Nightly Build v${{ steps.date.outputs.date }}'
          body: 'Nightly build based on the latest changes.'
          includeUpdaterJson: true
          draft: false
          prerelease: true
